import Head from "next/head";
import Spline from "@splinetool/react-spline";

export default function Home() {
  return (
    <>
      <Head>
        <title>3D Model App</title>
        <meta name="description" content="Generated by Mikhail Sumawan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <main className="w-full h-screen font-bodyFont bg-bodyColor text-textLight
      overflow-x-hidden overflow-y-scroll scrollbar scrollbar-track-bodyColor 
      scrollbar-thin scrollbar-thumb-textLight/60">
        <div className="h-[88vh] w-fullwidth pl-12 p-4">
          <section className="max-w-contentContainer mx-auto py-10 
          flex flex-col gap-4">
            <h1 className="mt-6 text-4xl font-titleFont text-textLight">
              3D Model Web App
            </h1>
          </section>

          <Spline scene="https://prod.spline.design/CsSr2PGlQtA7H60S/scene.splinecode" />
        </div>
        
      </main>
    </>
  );
}
